name: Surfguru Natal Diário

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:  


jobs:
  save-webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Download Webpage
        run: |
          wget -q --reject jpg,JPG,jpeg --adjust-extension --span-hosts --convert-links --no-directories --page-requisites --directory-prefix=2024 --tries=1 https://surfguru.com.br/previsao/brasil/rio-grande-do-norte/natal/oceanica 

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "webpage-${{ steps.date.outputs.date }}.html"
          git commit -m "Update webpage content"
          git push
