name: Surfguru Natal Diário

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:  


jobs:
  save-webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Download Webpage
        run: |
          python scrape.py

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "webpage-${{ steps.date.outputs.date }}.html"
          git commit -m "Update webpage content"
          git push
